# Generated by Django 5.1.1 on 2024-09-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('data_nasc', models.DateField()),
                ('cpf', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('altura', models.FloatField(max_length=2)),
                ('peso', models.FloatField(max_length=10)),
            ],
        ),
    ]
